Repository bandya2003/CRM-Website, pull requests merged in 2022-10, with the labels that each got.

#2 added html file
  main folder/index.html
Labels: enhancement, hacktoberfest-accepted

#3 Create style.css
  main folder/style.css
Labels: enhancement, hacktoberfest-accepted

#4 Create CSS.css
  CSS.css
Labels: enhancement, hacktoberfest-accepted

#5 Nice weather
  weather/Screenshot_1.png
  weather/niceweather.css
  weather/niceweather.html
Labels: enhancement, hacktoberfest-accepted

#6 Added Hospital Management
  Hospital-Management/README.md
  Hospital-Management/WebProject/WebContent/META-INF/MANIFEST.MF
  Hospital-Management/WebProject/WebContent/addDoctor.html
  Hospital-Management/WebProject/WebContent/addMedicine.html
  Hospital-Management/WebProject/WebContent/addPatient.html
  Hospital-Management/WebProject/WebContent/discharge.html
  Hospital-Management/WebProject/WebContent/getDoctor.html
  Hospital-Management/WebProject/WebContent/getMedicine.html
  Hospital-Management/WebProject/WebContent/getPatients.html
  Hospital-Management/WebProject/WebContent/index.html
  Hospital-Management/WebProject/WebContent/login.html
  Hospital-Management/WebProject/WebContent/newAssistant.html
  Hospital-Management/WebProject/WebContent/welcome.html
  Hospital-Management/WebProject/src/CreateAssistant.java
  Hospital-Management/WebProject/src/CreateDoctor.java
  Hospital-Management/WebProject/src/CreateMedicine.java
  Hospital-Management/WebProject/src/CreatePatient.java
  Hospital-Management/WebProject/src/Discharge.java
  Hospital-Management/WebProject/src/GetConnection.java
  Hospital-Management/WebProject/src/Login.java
  Hospital-Management/WebProject/src/Logout.java
  Hospital-Management/WebProject/src/RetrieveDoctor.java
  Hospital-Management/WebProject/src/RetrieveMedicine.java
  Hospital-Management/WebProject/src/RetrievePatients.java
  Hospital-Management/WebProject/src/RetrievePatientsDID.java
Labels: enhancement, hacktoberfest-accepted

#9 Added Weather Forecasting Website
  Weather Forecasting Website/README.md
  Weather Forecasting Website/index.html
  Weather Forecasting Website/script.js
Labels: enhancement, hacktoberfest-accepted

#8 [fix] weather app href
  weather/niceweather.html
Labels: enhancement, hacktoberfest-accepted

#10 Create index.html
  Zomato-Clone/index.html
Labels: enhancement, hacktoberfest-accepted

#11 Added college website project.
  College-Website-Project/ADMIN.jpg
  College-Website-Project/BMULOGO.jpg
  College-Website-Project/about.html
  College-Website-Project/about.jpg
  College-Website-Project/background.jpg
  College-Website-Project/banner.png
  College-Website-Project/banner2.jpg
  College-Website-Project/basketball.png
  College-Website-Project/blog.html
  College-Website-Project/cafeteria.png
  College-Website-Project/certificate.jpg
  College-Website-Project/contact.html
  College-Website-Project/course.html
  College-Website-Project/form-hendler.php
  College-Website-Project/index.html
  College-Website-Project/library.png
  College-Website-Project/logo.png
  College-Website-Project/london.png
  College-Website-Project/newyork.png
  College-Website-Project/style.css
  College-Website-Project/user1.jpg
  College-Website-Project/user2.jpg
  College-Website-Project/washington.png
Labels: enhancement, hacktoberfest-accepted

#12 Added project based on javascript
  Todo Project/assets/css/list.css
  Todo Project/assets/js/lib/jQuery.js
  Todo Project/assets/js/list.js
  Todo Project/list.html
Labels: enhancement, hacktoberfest-accepted

#13 Add Random Quote Generator
  Random Quote Generator/Favicon.png
  Random Quote Generator/index.html
  Random Quote Generator/script.js
  Random Quote Generator/style.css
Labels: documentation, hacktoberfest-accepted

#15 add: a minimal one page portfolio template
  Per-folio/.DS_Store
  Per-folio/README.md
  Per-folio/assets/.DS_Store
  Per-folio/assets/css/reset.css
  Per-folio/assets/css/style.css
  Per-folio/assets/images/.DS_Store
  Per-folio/assets/images/background.png
  Per-folio/assets/images/github.png
  Per-folio/assets/images/linkedin.png
  Per-folio/assets/images/overflow.png
  Per-folio/assets/images/per-folio.jpg
  Per-folio/index.html
Labels: enhancement, hacktoberfest-accepted

#16 Create index.html
  Student-Dashboard/index.html
Labels: enhancement, hacktoberfest-accepted

#18 Added gym website project
  Gym website Project/gym.html
  Gym website Project/gym.jpg
  Gym website Project/gymbg.jpg
Labels: enhancement, hacktoberfest-accepted

#20 Added a Library management program
  library management/library.py
Labels: documentation, enhancement

#23 Added a valuable Contribution
  test1.py
Labels: enhancement, hacktoberfest-accepted

#21 Added restaurant related nav bar in Zomato clone
  Zomato-Clone/index.html
Labels: enhancement, hacktoberfest-accepted

#22 Added result section in school website
  Student-Dashboard/index.html
Labels: enhancement, hacktoberfest-accepted

#25 Bgusin-Pomodoro-Timer
  Bagusin-Pomodoro-Timer/README.md
  Bagusin-Pomodoro-Timer/backtowork.mp3
  Bagusin-Pomodoro-Timer/break.mp3
  Bagusin-Pomodoro-Timer/button-sound.mp3
  Bagusin-Pomodoro-Timer/index.html
  Bagusin-Pomodoro-Timer/main.js
  Bagusin-Pomodoro-Timer/package-lock.json
  Bagusin-Pomodoro-Timer/package.json
  Bagusin-Pomodoro-Timer/styles.css
Labels: enhancement, hacktoberfest-accepted

#27 Added food delivery site
  Food Delivery/Style.css
  Food Delivery/contact.html
  Food Delivery/img1.png
  Food Delivery/img2.png
  Food Delivery/img3.webp
  Food Delivery/img4.png
  Food Delivery/index.html
  Food Delivery/logo.jpg
Labels: enhancement, hacktoberfest-accepted

#28 Create webcalculator.html
  webcalculator.html
Labels: enhancement, hacktoberfest-accepted

#29 Added the Char Counter.
  Char Counter/README.md
  Char Counter/index.html
  Char Counter/script.js
  Char Counter/style.css
Labels: enhancement, hacktoberfest-accepted

#32 Facebook login Page Clone
  Facebook Login Page clone/fblogin.html
  Facebook Login Page clone/fblogo2.png
  Facebook Login Page clone/style.css
Labels: enhancement, hacktoberfest-accepted

#33 EasyCalculator
  SimpleCalculator/CSS/style.css
  SimpleCalculator/HTML/index.html
  SimpleCalculator/IMG/calculatorTitle.png
  SimpleCalculator/JS/script.js
  SimpleCalculator/README.md
Labels: enhancement, hacktoberfest-accepted

#34 personal resume
  website/css/style.css
  website/favicon.ico
  website/html/contact_me.html
  website/image/my_image.png
  website/index.html
Labels: enhancement, hacktoberfest-accepted

#35 added html forms file
  All about Form In HTML/index.html
  All about Form In HTML/style.css
Labels: enhancement, hacktoberfest-accepted

#37 added a food card project
  FoodCard/burger2.png
  FoodCard/foodCard.html
  FoodCard/style.css
Labels: duplicate, hacktoberfest-accepted

#38 Issue solved of Text to Speech converter in Js
  Text-to-Speech-converter/Readme.md
  Text-to-Speech-converter/imgs/four.png
  Text-to-Speech-converter/imgs/one.png
  Text-to-Speech-converter/imgs/three.png
  Text-to-Speech-converter/imgs/two.png
  Text-to-Speech-converter/index.html
  Text-to-Speech-converter/script.js
  Text-to-Speech-converter/style.css
Labels: enhancement, hacktoberfest-accepted

#39 Ecommerce website
  Ecommerce/README.md
  Ecommerce/app.js
  Ecommerce/index.html
  Ecommerce/style.css
Labels: enhancement, hacktoberfest-accepted

#43 HacktoTempConverter - an web-app for temperature converter
  HacktoTempConverter/README.md
  HacktoTempConverter/imgs/arrow.svg
  HacktoTempConverter/imgs/default.png
  HacktoTempConverter/imgs/first.png
  HacktoTempConverter/imgs/second.png
  HacktoTempConverter/imgs/third.png
  HacktoTempConverter/index.css
  HacktoTempConverter/index.html
  HacktoTempConverter/script.js
Labels: enhancement, hacktoberfest-accepted

#42 temp
  Temp Converter/images/favicon.ico
  Temp Converter/images/temperature-converter.png
  Temp Converter/index.html
  Temp Converter/script.js
  Temp Converter/style.css
Labels: enhancement, hacktoberfest-accepted

#45 added a landing page website for gym
  Gym Website Landing Page/images/dumble.png
  Gym Website Landing Page/images/gym1.jpg
  Gym Website Landing Page/images/gym2.jpg
  Gym Website Landing Page/images/gym3.jpg
  Gym Website Landing Page/images/gym4.jpg
  Gym Website Landing Page/images/gym5.jpg
  Gym Website Landing Page/images/img1.jpg
  Gym Website Landing Page/images/shouting-at-gym.jpg
  Gym Website Landing Page/index.html
  Gym Website Landing Page/style.css
Labels: enhancement, hacktoberfest-accepted

#47 added a home page of a furniture ordering website
  Furniture Website Home Page/Images/chair1.png
  Furniture Website Home Page/Images/lamp2.png
  Furniture Website Home Page/Images/light1_1.png
  Furniture Website Home Page/index.html
  Furniture Website Home Page/style.css
Labels: enhancement, hacktoberfest-accepted

#46 Add files via upload
  jokeChromeExtension/logo.png
  jokeChromeExtension/manifest.json
  jokeChromeExtension/popup.html
  jokeChromeExtension/script.js
  jokeChromeExtension/style.css
Labels: enhancement, hacktoberfest-accepted

#50 Added disney website clone
  disneyHotstarClone/README.md
  disneyHotstarClone/images/add.png
  disneyHotstarClone/images/disney.png
  disneyHotstarClone/images/favicon.ico
  disneyHotstarClone/images/geographic.png
  disneyHotstarClone/images/logo.png
  disneyHotstarClone/images/marvel.png
  disneyHotstarClone/images/nxt.png
  disneyHotstarClone/images/pixar.png
  disneyHotstarClone/images/play.png
  disneyHotstarClone/images/poster 1.png
  disneyHotstarClone/images/poster 10.png
  disneyHotstarClone/images/poster 11.png
  disneyHotstarClone/images/poster 12.png
  disneyHotstarClone/images/poster 2.png
  disneyHotstarClone/images/poster 3.png
  disneyHotstarClone/images/poster 4.png
  disneyHotstarClone/images/poster 5.png
  disneyHotstarClone/images/poster 6.png
  disneyHotstarClone/images/poster 7.png
  disneyHotstarClone/images/poster 8.png
  disneyHotstarClone/images/poster 9.png
  disneyHotstarClone/images/pre.png
  disneyHotstarClone/images/slider1.png
  disneyHotstarClone/images/slider2.png
  disneyHotstarClone/images/slider3.png
  disneyHotstarClone/images/slider4.png
  disneyHotstarClone/images/slider5.png
  disneyHotstarClone/images/star-wars.png
  disneyHotstarClone/index.html
  disneyHotstarClone/index.js
  disneyHotstarClone/styles.css
  disneyHotstarClone/videos/disney.mp4
  disneyHotstarClone/videos/geographic.mp4
  disneyHotstarClone/videos/marvel.mp4
  disneyHotstarClone/videos/pixar.mp4
  disneyHotstarClone/videos/star-war.mp4
Labels: enhancement, hacktoberfest-accepted

#51 Added a frontend of food delivering website
  FoodOrderingWebsite/images/bg1.jpg
  FoodOrderingWebsite/images/bg3.jpg
  FoodOrderingWebsite/images/bg9.jpg
  FoodOrderingWebsite/images/bulk1.png
  FoodOrderingWebsite/images/burger1.png
  FoodOrderingWebsite/images/cont1.png
  FoodOrderingWebsite/images/cont2.png
  FoodOrderingWebsite/images/cont3.png
  FoodOrderingWebsite/images/cont4.png
  FoodOrderingWebsite/images/logo1.png
  FoodOrderingWebsite/images/order2.png
  FoodOrderingWebsite/index.html
  FoodOrderingWebsite/phone.css
  FoodOrderingWebsite/style.css
Labels: enhancement, hacktoberfest-accepted

#53 A new project simple dictionary web app added
  Simple Dictionary web app/README.md
  Simple Dictionary web app/index.html
  Simple Dictionary web app/index.js
  Simple Dictionary web app/style.css
Labels: enhancement, hacktoberfest-accepted

#56 Added NFT Preview Card Component
  NFT Preview Card Component/.vscode/settings.json
  NFT Preview Card Component/design/active-states.jpg
  NFT Preview Card Component/design/desktop-design.jpg
  NFT Preview Card Component/design/desktop-preview.jpg
  NFT Preview Card Component/design/mobile-design.jpg
  NFT Preview Card Component/design/style.css
  NFT Preview Card Component/images/favicon-32x32.png
  NFT Preview Card Component/images/icon-clock.svg
  NFT Preview Card Component/images/icon-ethereum.svg
  NFT Preview Card Component/images/icon-view.svg
  NFT Preview Card Component/images/image-avatar.png
  NFT Preview Card Component/images/image-equilibrium.jpg
  NFT Preview Card Component/index.html
Labels: enhancement, hacktoberfest-accepted

#57 Created FoodMart - web app for a Restaurant
  foodmart/.gitignore
  foodmart/README.md
  foodmart/package-lock.json
  foodmart/package.json
  foodmart/public/img/four.png
  foodmart/public/img/one.png
  foodmart/public/img/three.png
  foodmart/public/img/two.png
  foodmart/public/index.html
  foodmart/public/manifest.json
  foodmart/src/App.js
  foodmart/src/components/Api/MenuApi.js
  foodmart/src/components/Header/Header.css
  foodmart/src/components/Header/Header.jsx
  foodmart/src/components/ItemCard/ItemCard.css
  foodmart/src/components/ItemCard/ItemCard.jsx
  foodmart/src/components/MainCard/MainCard.jsx
  foodmart/src/index.js
  foodmart/src/setupTests.js
  foodmart/src/style.css
Labels: enhancement, hacktoberfest-accepted

#58 Added a Survey page
  survey_page
Labels: enhancement, hacktoberfest-accepted

#59 Create progress steps
  progress steps
Labels: enhancement, hacktoberfest-accepted

#63 added a random password generator
  random password generaor/README.md
  random password generaor/index.html
  random password generaor/pass.js
  random password generaor/style.css
Labels: enhancement, hacktoberfest-accepted

#64 Dice game added
  Dice Game/1.png
  Dice Game/README.md
  Dice Game/dice-1.png
  Dice Game/dice-2.png
  Dice Game/dice-3.png
  Dice Game/dice-4.png
  Dice Game/dice-5.png
  Dice Game/dice-6.png
  Dice Game/index.html
  Dice Game/pig-game-flowchart.png
  Dice Game/script.js
  Dice Game/style.css
Labels: enhancement, hacktoberfest-accepted

#65 Netflix clone added
  netflix clone/.env
  netflix clone/.eslintrc.js
  netflix clone/.gitignore
  netflix clone/README.md
  netflix clone/package-lock.json
  netflix clone/package.json
  netflix clone/public/favicon.ico
  netflix clone/public/index.html
  netflix clone/public/manifest.json
  netflix clone/public/robots.txt
  netflix clone/src/App.css
  netflix clone/src/App.js
  netflix clone/src/App.test.js
  netflix clone/src/components/Background.jsx
  netflix clone/src/components/Body.js
  netflix clone/src/components/NavBar.js
  netflix clone/src/components/Todo.jsx
  netflix clone/src/components/Todos.jsx
  netflix clone/src/components/index.js
  netflix clone/src/images/background.jpg
  netflix clone/src/index.css
  netflix clone/src/index.js
  netflix clone/src/logo.svg
  netflix clone/src/setupTests.js
  netflix clone/src/styles/background.css
  netflix clone/src/styles/todo.css
Labels: enhancement, hacktoberfest-accepted

#67 Created form using html only
  Form using html
Labels: enhancement, hacktoberfest-accepted

#68 Created Flipkart front page using html
  Flipkart front page clone
Labels: enhancement, hacktoberfest-accepted

#69 Created Amazon clone front page.
  Amazon sign in clone.
Labels: enhancement, hacktoberfest-accepted

#72 Created Twitter clone page
  Twitter clone page
Labels: enhancement, hacktoberfest-accepted

#71 Created Netflix front page using html and css
  Netflix clone front page
Labels: enhancement, hacktoberfest-accepted

#73 Instagram Clone.html
  Instagram Clone.html
Labels: enhancement, hacktoberfest-accepted

#75 Symbol Recognition.py
  Symbol Recognition.py
Labels: enhancement, hacktoberfest-accepted

#76 Create dad jokes
  dad jokes
Labels: enhancement, hacktoberfest-accepted

#77 file system organizer
  file_system_organizer-main/file_system_organizer/commands/help.js
  file_system_organizer-main/file_system_organizer/commands/organize.js
  file_system_organizer-main/file_system_organizer/commands/tree.js
  file_system_organizer-main/file_system_organizer/main.js
  file_system_organizer-main/file_system_organizer/package-lock.json
  file_system_organizer-main/file_system_organizer/package.json
  file_system_organizer-main/file_system_organizer/readme.md
Labels: enhancement, hacktoberfest-accepted

#60 Create progress steps
  progress steps
Labels: enhancement, hacktoberfest-accepted

#78 Add a file containing various types of toggle buttons
  toggle/index.html
Labels: documentation, enhancement, hacktoberfest-accepted

#79 react-shopping-cart
  react-shopping-cart/README.md
  react-shopping-cart/Screenshot 2021-06-06 at 13.07.18.png
  react-shopping-cart/package.json
  react-shopping-cart/public/favicon.ico
  react-shopping-cart/public/images/cart.png
  react-shopping-cart/public/images/empty-cart.png
  react-shopping-cart/public/images/logo.png
  react-shopping-cart/public/images/peproni.png
  react-shopping-cart/public/images/pizza.png
  react-shopping-cart/public/index.html
  react-shopping-cart/public/manifest.json
  react-shopping-cart/public/robots.txt
  react-shopping-cart/src/App.js
  react-shopping-cart/src/CartContext.js
  react-shopping-cart/src/Index.css
  react-shopping-cart/src/components/Navigation.js
  react-shopping-cart/src/components/Product.js
  react-shopping-cart/src/components/Products.js
  react-shopping-cart/src/helpers.js
  react-shopping-cart/src/index.js
  react-shopping-cart/src/pages/About.js
  react-shopping-cart/src/pages/Cart.js
  react-shopping-cart/src/pages/Home.js
  react-shopping-cart/src/pages/ProductsPage.js
  react-shopping-cart/src/pages/SingleProduct.js
  react-shopping-cart/yarn.lock
Labels: enhancement, hacktoberfest-accepted

#80 Create Cookies.html
  Cookies.html
Labels: enhancement, hacktoberfest-accepted

#85 Create minesweeper.js
  minesweeper.js
Labels: enhancement, hacktoberfest-accepted

#84 Create race_game.html
  race_game.html
Labels: enhancement, hacktoberfest-accepted

#83 Youtube_video_Downloader
  Youtube Video Downloader/youtube_downloader.py
Labels: enhancement, hacktoberfest-accepted

#82 Added a chatbox application
  ChatBox/README.md
  ChatBox/package-lock.json
  ChatBox/package.json
  ChatBox/public/chat.html
  ChatBox/public/css/style.css
  ChatBox/public/index.html
  ChatBox/public/js/main.js
  ChatBox/server.js
  ChatBox/utils/messages.js
  ChatBox/utils/users.js
Labels: enhancement, hacktoberfest-accepted

#81 Functionalities added
  Charts.html
  PopUp.html
  Promise.html
Labels: enhancement, hacktoberfest-accepted

#86 Updated dad jokes
  dad jokes
Labels: enhancement, hacktoberfest-accepted

#93 React Quiz app
  quiz-app/README.md
  quiz-app/package-lock.json
  quiz-app/package.json
  quiz-app/public/favicon.ico
  quiz-app/public/index.html
  quiz-app/public/logo192.png
  quiz-app/public/logo512.png
  quiz-app/public/manifest.json
  quiz-app/public/robots.txt
  quiz-app/src/App.css
  quiz-app/src/App.js
  quiz-app/src/App.test.js
  quiz-app/src/component/Button.js
  quiz-app/src/component/Page404.js
  quiz-app/src/component/Question.js
  quiz-app/src/component/Quiz.js
  quiz-app/src/index.css
  quiz-app/src/index.js
  quiz-app/src/logo.svg
  quiz-app/src/reportWebVitals.js
  quiz-app/src/setupTests.js
Labels: enhancement, hacktoberfest-accepted

#92 Added Password Generator
  Password Generator/PasswordGenerator.py
Labels: enhancement, hacktoberfest-accepted

#91 Added pdf/Book Reading
  AI PDF BOOK READING/ai4book.py
Labels: enhancement, hacktoberfest-accepted

#90 added Music Player
  Music Player/music_player.py
Labels: enhancement, hacktoberfest-accepted

#89 Create decimal_to_hexadecimal.js
  decimal_to_hexadecimal.js
Labels: enhancement

#88 Employ Registration Form
  Employ Registration Form/employregistration.html
Labels: enhancement, hacktoberfest-accepted

#94 calulator app using js
  app.js
  index.html
  style.css
Labels: enhancement, hacktoberfest-accepted
